Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-09, with the labels that each got.

#50 [PRDP-127] feat: Refactoring receipt-pdf-datastore generate PDF function into receipt-pdf-generator
  .env.example
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_blob_storage_client.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  integration-test/src/step_definitions/reqeipt_queue_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/PdfEngineClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptBlobClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/ReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/BizEventNotValidException.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfEngineErrorMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfEngineErrorResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfGeneration.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfMetadata.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/request/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/response/BlobStorageResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/response/PdfEngineResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/TemplateMapperUtils.java
  src/main/resources/complete_template.zip
  src/main/resources/partial_template.zip
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueueTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessagesTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/PdfEngineClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptBlobClientImplTest.java
Labels: enhancement, help wanted, size/large, major

#51 [fix] Updated app name in Chart.yaml
  helm/Chart.yaml
Labels: size/small, patch

#53 fix: Show log on console, application insight and elastic
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: bug, size/small, patch

#54 fix: Change agent from apm to otl
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#55 fix: Fix dockerfile
  Dockerfile
Labels: bug, size/small, patch

#56 [PRDP-129] feat: Added total notice filter
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: enhancement, size/small, minor

#58 [PRDP-123] feat: Use deployment selfhosted runner for integration test
  .github/workflows/integration_test.yml
  integration-test/src/package.json
Labels: enhancement, skip, size/small

#57 [PRDP-133] fix: Change log service name
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java
  src/main/resources-filtered/application.properties
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/InfoTest.java
  src/test/resources/META-INF/maven/it.gov.pagopa.receipt.pdf.datastore/receipt-pdf-datastore/pom.properties
Labels: bug, size/small, patch

#61 Revert "[fix] Fixed totalNotice filter control on null value"
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: size/small

#62 [fix] Fixed totalNotice filter control on null value
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: size/small, patch

#63 [PRDP-135] Added receipt's timestamps
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
Labels: enhancement, size/small, minor

#59 [PRDP-124] Modified performance test following refactor
  performance-test/src/receipt_processor.js
Labels: size/small, patch

#64 [PRDP-136] Added performance test to simulate prod load
  .devops/performance-test-pipelines.yml
  performance-test/src/DockerfileReview
  performance-test/src/DockerfileTeardown
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/common.js
  performance-test/src/modules/datastore_client.js
  performance-test/src/package.json
  performance-test/src/receipt_flow_simulation.js
  performance-test/src/scripts/README.md
  performance-test/src/scripts/review_script.js
  performance-test/src/scripts/scripts_common.js
  performance-test/src/scripts/teardown_script.js
  performance-test/src/test-types/constant-prod.json
  performance-test/src/uat.environment.json
Labels: enhancement, size/large

#65 fix: deploy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch

#66 [feat] Lowered max replica to 1
  helm/values-uat.yaml
Labels: enhancement, size/small
