Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-06, with the labels that each got.

#2 [PRDP-15] ci: Updated check and assign on pr workflows
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
Labels: ignore-for-release, skip

#4 [PRDP-15] ci: Updated deploy workflow to avoid using azure pipelines
  .devops/deploy-pipelines-aks.yml
  .devops/deploy-pipelines-standard.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release-deploy.yml
Labels: ignore-for-release, skip

#3 [PRDP-15] ci: Updated code review worklows using only github actions
  .devops/code-review-pipelines.yml
  .github/workflows/code_review.yml
  .github/workflows/sonar_analysis.yml
Labels: ignore-for-release, skip

#10 [PRDP-17] Cleaned code - added unit tests - documented code
  README.md
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptQueueClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfEngineErrorMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfEngineErrorResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfGeneration.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/PdfMetadata.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/request/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/response/BlobStorageResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/response/PdfEngineResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/ObjectMapperUtils.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/ReceiptPdfUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/util/ObjectMapperUtilsTest.java
Labels: enhancement, size/large

#12 [PRDP-50] Update sonarcloud and refine logs
  README.md
Labels: documentation, size/small, patch

#13 [PRDP-50] fix: updated helm charts dev values to fix websitename
  helm/values-dev.yaml
Labels: size/small, patch

#14 [PRDP-17] Reach unit tests coverage
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/BizEventNotValidException.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/PdfEngineClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptBlobClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptQueueClientImplTest.java
Labels: enhancement, size/small

#15 [PRDP-48] ci: updated uat helm chart
  helm/values-uat.yaml
Labels: size/small, minor

#18 fix: Numerous fixes and code improvements
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptQueueClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/BizEventNotValidException.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/ReceiptNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/ObjectMapperUtils.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/TemplateMapperUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/util/ObjectMapperUtilsTest.java
Labels: size/large

#21 fix: Improved memory usage
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptBlobClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/request/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/response/PdfEngineResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/PdfEngineClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptBlobClientImplTest.java
  src/test/resources/output.pdf
Labels: enhancement, size/small

#19 [PRDP-21] feat: Add integration test
  .env.example
  .github/workflows/code_review.yml
  .gitignore
  .identity/00_data.tf
  .identity/02_application_action.tf
  .identity/03_github_environment.tf
  docker/README.md
  docker/docker-compose.yml
  docker/run_docker.sh
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/config/properties.json
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/biz_events_datastore_client.js
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_blob_storage_client.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  integration-test/src/step_definitions/reqeipt_queue_client.js
Labels: enhancement, size/large, minor
