Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-11, with the labels that each got.

#82 [PRDP-183] Implement PDV Tokenizer for fiscal codes
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  performance-test/src/modules/common.js
  performance-test/src/scripts/review_script.js
  performance-test/src/scripts/teardown_script.js
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/PDVTokenizerClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PDVTokenizerClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/PDVTokenizerException.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/ErrorResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/InvalidParam.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/PiiResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/TokenResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/PDVTokenizerService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PDVTokenizerClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptQueueClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImplTest.java
Labels: enhancement, size/large, minor

#83 fix: Selfhost runner integtest
  .github/workflows/integration_test.yml
Labels: size/small

#84 [chore] Tokenizer improvements
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReasonErrorCode.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/PDVTokenizerUnexpectedException.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/ErrorMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/tokenizer/ErrorResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/PDVTokenizerServiceRetryWrapper.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceRetryWrapperImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceRetryWrapperImplTest.java
Labels: size/large, patch

#85 fix: Tokenizer error response mapping
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/PDVTokenizerServiceImpl.java
Labels: size/small, patch

#86 fix tokenier path
  helm/values-prod.yaml
Labels: size/small

#89 [fix] Updated reason error codes
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PDVTokenizerClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReasonErrorCode.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
Labels: size/small, patch

#90 feat: Add health function
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Health.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/HealthTest.java
Labels: enhancement, size/small, patch

#87 Feat add failed recovery endpoint
  .env.example
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/BizEventCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/BizEventCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/BizEventNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/ReceiptFailedRecoveryRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/BizEventCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImplTest.java
Labels: size/large, minor

#91 feat: Introduced openapi, updated helm values
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
Labels: size/small, patch

#93 fix: Payeename for notify
  .gitignore
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: size/small

#94 fix payeename
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: size/small

#92 Feat add fail recovery int test
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  openapi/openapi.json
Labels: skip, size/small

#95 Chore prod test script
  performance-test/src/scripts/prod_test_script.js
Labels: size/small

#97 [chore] Improved prod test script to not save receipts already existing
  performance-test/src/scripts/prod_test_script.js
Labels: skip, size/small

#98 fix: missing check in integration check steps js
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/03_github_environment.tf
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.uat
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
Labels: bug, skip, size/small

#99 [PRDP-220] Fix queue-cosmos desync
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReasonErrorCode.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/RecoverFailedReceiptTest.java
Labels: size/large, minor

#100 [PRDP-224] Changed Remittance Information retrieve logic
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/ObjectMapperUtilsTest.java
Labels: size/large, patch

#102 [PRDP-232] chore: removing recover failed source
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/03_github_environment.tf
  README.md
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RecoverFailedReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/BizEventCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/BizEventCosmosClientImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/RecoverFailedReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/BizEventCosmosClientImplTest.java
Labels: size/large, minor

#103 [PRDP-258] Added new Receipt status TO_REVIEW
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReceiptStatusType.java
Labels: size/small, patch
