Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-10, with the labels that each got.

#67 [PRDP-104] feat: introducing cart data for notification in receipt
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/CartItem.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/EventData.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: size/small, patch

#69 [feat] Added IUR info to match biz event datastore's entity
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/DebtorPosition.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/PaymentInfo.java
Labels: size/small, patch

#70 fix: Add amount to notify
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
Labels: size/small

#71 [PRDP-155] feat: Added JsonIgnoreProperties ignoreUnknown to BizEvent's entities
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/AuthRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/BizEvent.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Creditor.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Debtor.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/DebtorPosition.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Details.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/MBD.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/MapEntry.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Payer.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/PaymentInfo.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Psp.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Transaction.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/TransactionDetails.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/TransactionPsp.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/User.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/WalletItem.java
Labels: enhancement, size/small, patch

#74 [fix] Fixed blob deletion
  performance-test/src/scripts/teardown_script.js
Labels: bug, ignore-for-release, size/small

#75 fix: Prod-deploy
  .identity/00_data.tf
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#76 Chore: removed otl in prod as mitigation
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, skip, size/small

#77 Feat: add discarder for anonym debtor
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: size/small, patch

#78 [PRDP-164] feat: Added specific section for payer error in receipt
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java
Labels: size/small, patch

#80 [PRDP-193] Migrate to java17
  .github/maven_code_review/action.yml
  .github/workflows/code_review.yml
  Dockerfile
  host.json
  pom.xml
Labels: size/small, minor
