Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-07, with the labels that each got.

#23 [PRDP-56] feat: update with poison queue management functions
  .github/workflows/release-deploy.yml
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/BizEvent.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/ReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReceiptErrorStatusType.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/exception/UnableToQueueException.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueueTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessagesTest.java
Labels: enhancement, size/large, minor

#24 [fix-uat-env] Fixed receipt poison topic uat env
  helm/values-uat.yaml
Labels: size/small, patch

#25 [PRDP-58] feat: Updated logs for datastore processes
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
Labels: size/small, patch

#26 [PRDP-59] feat: Add poison queue test to integration test
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/biz_events_datastore_client.js
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_blob_storage_client.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  integration-test/src/step_definitions/reqeipt_queue_client.js
Labels: enhancement, minor

#27 [PRDP-23] feat: added performance tests
  .devops/performance-test-pipelines.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/common.js
  performance-test/src/modules/datastore_client.js
  performance-test/src/receipt_processor.js
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/enumeration/ReceiptStatusType.java
Labels: documentation, enhancement, size/large

#30 [PRDP-74] Export JMX Metrics to Prometheus
  Dockerfile
  agent/config.yaml
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/request/PdfEngineRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
Labels: size/small, minor

#31 [PRDP-75] Tuning performance tests
  .devops/performance-test-pipelines.yml
  helm/values-uat.yaml
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/test-types/constant.json
  performance-test/src/uat.environment.json
Labels: enhancement, size/small, patch

#32 fixed PdfEngineClientImplTest
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/PdfEngineClientImplTest.java
Labels: bug, size/small

#35 fix: host json
  host.json
Labels: size/small

#34 [PRDP-93] fix run_docker.sh script
  docker/run_docker.sh
Labels: bug, size/small
