Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-12, with the labels that each got.

#104 [fix] Fixed integration tests delete
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
Labels: bug, skip, size/small

#105 [feat] Added new fields name and surname to bizEvent User class
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/User.java
Labels: size/small, patch

#109 [PRDP-281] feat: add payer fiscal code from details
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: size/small, patch

#110 [PRDP-282] feat: Add check to discard already processed biz-events
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: size/small, patch

#112 [PRDP-301] feat: Discard ecommerce events
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/resources/logback-test.xml
Labels: size/small, minor
