Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2023-08, with the labels that each got.

#36 [PRDP-85] fix: Added info response body with services info
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/model/AppInfo.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/InfoTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/util/HttpResponseMessageMock.java
  src/test/resources/META-INF/maven/it.gov.pagopa.receipt.pdf.datastore/receipt-pdf-datastore/pom.properties
Labels: bug, size/small, patch

#37 [PRDP-85] fix: Info endpoint response
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java
  src/main/resources-filtered/application.properties
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/InfoTest.java
Labels: bug, size/small, patch

#33 [prf-test-tuning] Changed Constant scenario settings
  performance-test/src/test-types/constant.json
Labels: size/small

#38 fix: Identity
  .identity/02_application_action.tf
Labels: size/small

#39 [PRDP-95] add apm agent and logback
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
  src/main/resources/logback.xml
Labels: size/small, patch

#41 [PRDP-107] fix: Configure k6 to not ignore response body
  performance-test/README.md
  performance-test/src/modules/datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/GenerateReceiptPdfService.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/ManageReceiptPoisonQueueTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/RetryReviewedPoisonMessagesTest.java
Labels: bug, size/small, patch

#44 fix: Aks limit
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch

#45 fix: Mem req
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#47 [PRDP-117] fix: Fixed indentation notify action
  .github/workflows/integration_test.yml
Labels: size/small, patch, minor

#49 [fix] Fixed integration-test action notification
  .github/workflows/integration_test.yml
Labels: skip, size/small, patch
