Repository pagopa/pagopa-receipt-pdf-datastore, pull requests merged in 2024-01, with the labels that each got.

#113 [PRDP-293] fix: Biz-event model
  integration-test/src/step_definitions/common.js
  performance-test/src/modules/common.js
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/Transaction.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/event/enumeration/UserType.java
Labels: size/small, patch

#108 [PRDP-274] feat: Add handle cart receipt function
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/BizEventCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/BizEventCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/cart/CartForReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/CartItem.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/EventData.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/IOMessageData.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/ReasonError.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/receipt/ReceiptMetadata.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/BizEventToReceiptService.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/BizEventCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/CartReceiptsCosmosClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
Labels: enhancement, size/large, minor

#114 [PRDP-308] feat: Add feature flag for cart processing
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
Labels: size/small, patch

#116 fix: Add cart status check
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceiptTest.java
Labels: size/small, patch

#117 chore: Upd helm prod
  helm/values-prod.yaml
Labels: skip, size/small

#118 [PRDP-314] fix: GrandTotal format
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: bug, size/small, patch

#115 [PRDP-311] feat: Updated integration tests for cart implementation
  helm/values-dev.yaml
  helm/values-uat.yaml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/biz_events_datastore_client.js
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/CartReceiptsCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/CartReceiptsCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/entity/cart/CartForReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
Labels: enhancement, size/small, patch

#120 [PRDP-328] fix: Fixed typo in int test
  integration-test/src/step_definitions/receipt_pdf_datastore_step.js
Labels: size/small, patch

#123 [PRDP-333] fix: Amount format
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: bug, size/small

#121 [PRDP-332] Improved fiscal code validation and logic
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
Labels: skip, size/small

#119 [PRDP-323] Added channel origin verification for payer CF
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/CartEventToReceipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/BizEventToReceiptTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
Labels: minor

#124 [PRDP-337] fix: Changed payer taxCode retrieval order
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
Labels: bug, size/small, patch

#125 fix: Discard check on invalid fiscal code
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: bug, size/small, patch

#126 fix: Add origin check
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/service/impl/BizEventToReceiptServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
Labels: size/small, patch

#127 [PRDP-335] Introduced remittance information check with regex against unwanted strings
  src/main/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/datastore/utils/BizEventToReceiptUtilsTest.java
Labels: bug, size/small, patch
